overlay: drop more aarch64 references
These don't evaluate anymore because of

    error: attribute 'hostPlatform' missing

and right now these aren't needed anyways.